<?php

namespace NbsPhp\Core\Models;

use Carbon\Carbon;
use NbsPhp\Core\Models\Model;

/**
 * @property int           $id
 * @property string        $name
 * @property int           $user_id
 * @property AuthModel     $user
 * @property int|string    $provider_id unique id generated by provider
 * @property int|string    $provider_token token generated by provider
 * @property string        $provider
 * @property string        $avatar
 * @property Carbon|string $created_at
 * @property Carbon|string $updated_at
 */
class UserOAuthModel extends AbstractModel
{
    const PROVIDER_GOOGLE = 'google';
    const PROVIDER_FACEBOOK = 'facebook';
    const PROVIDER_APPLE = 'apple';

    protected $table = 'user_oauth';

    protected $fillable = [
        'name',
        'user_id',
        'provider',
        'provider_id',
        'provider_token',
        'avatar',
        'created_at',
        'updated_at',
    ];

    public function user()
    {
        return $this->belongsTo(AuthModel::class, 'user_id');
    }
}
