[xdebug]
; 3.0 version

; to disabled xdebug, set off
; xdebug.mode = off

; xdebug.mode = ${PHP_XDEBUG_MODE} -> xdebug.remote_enable (1)
; xdebug.client_host = ${PHP_XDEBUG_CLIENT_HOST} -> xdebug.remote_enable
; xdebug.client_port = ${PHP_XDEBUG_CLIENT_PORT} -> xdebug.remote_host
; xdebug.discover_client_host = ${PHP_XDEBUG_DISCOVER_CLIENT_HOST} -> xdebug.remote_port [yes,no,default,trigger]
; xdebug.start_with_request = yes -> xdebug.remote_autostart
; xdebug.idekey = ${PHP_XDEBUG_IDEKEY}

; profiling
; xdebug.output_dir = ${PHP_XDEBUG_OUTPUT_DIR}

; 2.0 version
; xdebug.default_enable = ${PHP_XDEBUG_DEFAULT_ENABLE} -> xdebug.mode
xdebug.remote_enable = ${PHP_XDEBUG_REMOTE_ENABLE}
xdebug.remote_port = ${PHP_XDEBUG_CLIENT_HOST}
xdebug.remote_host = ${PHP_XDEBUG_CLIENT_PORT}
; remote_connect_back is not safe in production!
xdebug.remote_connect_back = ${PHP_XDEBUG_REMOTE_CONNECT_BACK}
xdebug.remote_autostart = yes
xdebug.profiler_enable = ${PHP_XDEBUG_PROFILER_ENABLE}
xdebug.profiler_output_dir = ${PHP_XDEBUG_PROFILER_OUTPUT_DIR}
xdebug.idekey = ${PHP_XDEBUG_IDEKEY}
