stages:
  - base
  - lint
  - build
  - deploy

base-php-7.4:
  stage: base
  environment:
    name: development
  image: docker:stable
  script:
    - docker build -t $CI_REGISTRY_IMAGE/base:latest -f ./deployments/v2/php-7.4/runtime/Dockerfile .
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/base:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/base:latest
  only:
    refs:
      - develop
    changes:
      - "deployments/v2/php-7.4/runtime/**/*"
  tags:
    - docker-runner

base-lint:
  stage: base
  environment:
    name: development
  image: docker:stable
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE/lint:latest -f ./deployments/v2/php-7.4/lint/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/lint:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/lint:latest
  only:
    refs:
      - develop
    changes:
      - "deployments/v2/php-7.4/lint/**/*"
  tags:
    - docker-runner

base-vendor:
  stage: base
  environment:
    name: development
  image: docker:stable
  script:
    - docker build -t $CI_REGISTRY_IMAGE/vendor:latest -f ./deployments/v2/vendor/Dockerfile .
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}/vendor:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/vendor:latest
  only:
    refs:
      - develop
    changes:
      - "deployments/v2/vendor/**/*"
      - "composer.json"
      - "composer.lock"
  tags:
    - docker-runner

lint-php:
  stage: lint
  environment:
    name: development
  image: $CI_REGISTRY_IMAGE/lint:latest
  needs:
    - job: base-lint
      optional: true
  script:
    - composer install --ignore-platform-reqs
    - phpstan analyse -c phpstan.neon.dist --no-progress --error-format=junit > phpstan.xml
  artifacts:
    when: on_failure
    paths:
      - phpstan.xml
    reports:
      junit: phpstan.xml
  when: always
  only:
    refs:
      - merge_requests
    changes:
      - "packages/sanf/**/*"
  tags:
    - docker-runner
  allow_failure: true

build-api:
  stage: build
  environment:
    name: development
  image: nbsdev/docker-builder:20
  needs:
    - job: base-vendor
      optional: true
    - job: base-php-7.4
      optional: true
  script:
    - cp $ASSET_LINKS_FILE $CI_PROJECT_DIR/public/.well-known/assetlinks.json
    - cp $APPLE_SITE_ASSOCIATION_FILE $CI_PROJECT_DIR/public/.well-known/apple-site-association
    - cp $FIREBASE_SA_FILE $CI_PROJECT_DIR/config/firebase-keys/firebase.json
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE/api:latest -f ./deployments/v2/app/api/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/api:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/api:latest
  only:
    - develop
  tags:
    - docker-runner

build-worker:
  stage: build
  environment:
    name: development
  image: nbsdev/docker-builder:20
  needs:
    - job: base-vendor
      optional: true
    - job: base-php-7.4
      optional: true
  script:
    - cp $FIREBASE_SA_FILE $CI_PROJECT_DIR/config/firebase-keys/firebase.json
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE/worker:latest -f ./deployments/v2/app/worker/Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/worker:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/worker:latest
  only:
    - develop
  tags:
    - docker-runner

deploy-dev:
  stage: deploy
  image: docker:stable
  before_script:
    - cd $CI_PROJECT_DIR
  needs:
    - job: build-api
      optional: true
    - job: build-worker
      optional: true
  script:
    - cp $ENV_FILE ./.env
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker-compose -f docker-compose.dev.yml pull
    - docker-compose -f docker-compose.dev.yml up --build --force-recreate -d
  only:
    - develop
  tags:
    - sanfind-api-runner