# Set error page location and page html
error_page 404 $error_resp;
error_page 403 /403.html;

location = /404.html {
    add_header Content-Security-Policy "default-src 'self'; font-src 'self' fonts.googleapis.com fonts.gstatic.com; style-src 'self' fonts.googleapis.com fonts.gstatic.com; form-action 'none'; frame-ancestors 'none';" always;
    add_header X-Content-Type-Options nosniff;
    root /var/www/html;
    internal;
}

location = /403.html {
    add_header Content-Security-Policy "default-src 'self'; font-src 'self' fonts.googleapis.com fonts.gstatic.com; style-src 'self' fonts.googleapis.com fonts.gstatic.com; form-action 'none'; frame-ancestors 'none';" always;
    add_header X-Content-Type-Options nosniff;
    root /var/www/html;
    internal;
}

location = /error-page.css {
    add_header Content-Security-Policy "default-src 'self'; font-src 'self' fonts.googleapis.com fonts.gstatic.com; style-src 'self' fonts.googleapis.com fonts.gstatic.com; form-action 'none'; frame-ancestors 'none';" always;
    add_header X-Content-Type-Options nosniff;
    root /var/www/html;
}

location = /404.json {
    add_header Content-Type application/json ;
    root /var/www/json;
    internal;
}
