name: Client Credential
abbreviation: client_app_credential
checker: PragmaRX\Health\Checkers\Expression
notify: true
column_size: 3
error_message: "There is missing app client id or secret defined"
graph_enabled: false
targets:
  - default:
      expression_value: "env('APP_CLIENT_ID') != null && env('APP_CLIENT_SECRET') != null"
      should_return: true
