server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/app/public;

    index index.html index.htm index.php;

    server_name localhost;

    server_tokens off;

    charset utf-8;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    location / {
        set $uri_path $uri;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    client_max_body_size 32M;

    location ~ \.php$ {
        #include snippets/fastcgi-php.conf;
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_read_timeout 600;
        fastcgi_index index.php;
        fastcgi_pass unix:/usr/local/var/run/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTP_X_REQUEST_ID $request_id;
        fastcgi_param REQUEST_PATH $uri_path;
        fastcgi_buffers 4 256k;
        fastcgi_buffer_size 128k;
        fastcgi_intercept_errors on;
    }

    include snippets/error-page.conf;

    location ~ /\.ht {
        deny all;
    }

    include h5bp/basic.conf;
}

map $http_accept $error_resp {
    default /404.html;
    ~application/json /404.json;
}

map $http_content_type $error_resp {
    default /404.html;
    ~application/json /404.json;
}
