<?php

return [
    'is_production' => (bool) env('MIDTRANS_IS_PRODUCTION', false),
    'server_key' => env('MIDTRANS_SERVER_KEY'),
    'client_key' => env('MIDTRANS_CLIENT_KEY'),
    'is_sanitized' => (bool) env('MIDTRANS_IS_SANITIZED', true),
    'is_3ds' => (bool) env('MIDTRANS_IS_3DS', true),
    'snap' => [
        'expiry' => [
            'unit' => env('MIDTRANS_EXPIRY_UNIT', 'minutes'),
            'duration' => (int) env('MIDTRANS_EXPIRY_DURATION', 30),
        ],
    ],
    'enabled_payments' => ['bank_transfer'],

    'logo' => [
        'disk' => env('MIDTRANS_LOGO_DISK'),
        'directory' => env('MIDTRANS_LOGO_DIRECTORY', 'midtrans-logo'),
        'map' => [
            'akulaku_paylater' => 'akulaku_paylater.png',
            'akulaku_paylater_standard_single_graphic' => 'akulaku_paylater_standard_single_graphic.png',
            'akulaku_paylater_standard_white' => 'akulaku_paylater_standard_white.png',
            'akulaku_paylater_standard_white_graphic' => 'akulaku_paylater_standard_white_graphic.png',
            'alfamart' => 'alfamart.png',
            'american_express' => 'american_express.png',
            'bank_mega' => 'bank_mega.png',
            'bank_transfer_network_alto' => 'bank_transfer_network_alto.png',
            'bank_transfer_network_atm_bersama' => 'bank_transfer_network_atm_bersama.png',
            'bank_transfer_network_prima' => 'bank_transfer_network_prima.png',
            'bca' => 'bca.png',
            'bca_klikpay' => 'bca_klikpay.png',
            'bni' => 'bni.png',
            'bri' => 'bri.png',
            'cimb_clicks' => 'cimb_clicks.png',
            'cimbniaga' => 'cimbniaga.png',
            'cimb' => 'cimbniaga.png',
            'dan+dan' => 'dan+dan.png',
            'danamon' => 'danamon.png',
            'epay_bri' => 'epay_bri.png',
            'gopay' => 'gopay.png',
            'gopay_brandmark' => 'gopay_brandmark.svg',
            'gopay_gopaylater_ojk' => 'gopay_gopaylater_ojk.png',
            'gopay_horizontal' => 'gopay_horizontal.svg',
            'gopay_landscape' => 'gopay_landscape.png',
            'gopay_landscape_white' => 'gopay_landscape_white.png',
            'gopay_logogram' => 'gopay_logogram.png',
            'gopay_logogram_white' => 'gopay_logogram_white.png',
            'gopay_vertical' => 'gopay_vertical.svg',
            'gopay_white' => 'gopay_white.png',
            'gopaylater_horizontal' => 'gopaylater_horizontal.png',
            'i-saku' => 'i-saku.png',
            'indomaret' => 'indomaret.png',
            'jcb' => 'jcb.png',
            'jcb_secure' => 'jcb_secure.png',
            'klik_bca' => 'klik_bca.png',
            'kredivo' => 'kredivo.png',
            'linepay' => 'linepay.png',
            'mandiri' => 'mandiri.png',
            'mandiri_atm' => 'mandiri_atm.png',
            'mandiri_clickpay' => 'mandiri_clickpay.png',
            'mandiri_ecash' => 'mandiri_ecash.png',
            'mastercard' => 'mastercard.png',
            'mastercard_secure' => 'mastercard_secure.png',
            'maybank' => 'maybank.png',
            'permata' => 'permata_bank.png',
            'permata_bank' => 'permata_bank.png',
            'qris' => 'qris.png',
            'shopeepay' => 'shopeepay.png',
            'shopeepay_qris_1' => 'shopeepay_qris_1.png',
            'shopeepay_qris_2' => 'shopeepay_qris_2.png',
            'shopeepay_qris_3' => 'shopeepay_qris_3.png',
            'shopeepay_rectangle_orange' => 'shopeepay_rectangle_orange.png',
            'shopeepay_rectangle_white' => 'shopeepay_rectangle_white.png',
            'shopeepay_square_orange' => 'shopeepay_square_orange.png',
            'shopeepay_square_white' => 'shopeepay_square_white.png',
            'uob_ezpay' => 'uob_ezpay.png',
            'uob_ezpay_horizontal' => 'uob_ezpay_horizontal.png',
            'verified_visa' => 'verified_visa.png',
            'visa' => 'visa.png',
        ],
    ],

];
