<?php

namespace Sanf\Core\Modules\User;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use NbsPhp\Core\Models\AbstractModel;
use Sanf\Core\Constants\ConnectionDB;
use Sanf\Core\Traits\SodiumEncryptionTrait;

/**
 * Encrypted model version for UserOAuthModel.
 * @see \NbsPhp\Core\Models\UserOAuthModel
 *
 * @property int           $id
 * @property string        $name
 * @property int           $user_id
 * @property AuthModel     $user
 * @property int|string    $provider_id unique id generated by provider
 * @property int|string    $provider_token token generated by provider
 * @property string        $provider
 * @property string        $avatar
 * @property Carbon|string $created_at
 * @property Carbon|string $updated_at
 */
class UserOAuthEncryptedModel extends AbstractModel
{
    use SoftDeletes, SodiumEncryptionTrait;

    const PROVIDER_GOOGLE = 'google';
    const PROVIDER_FACEBOOK = 'facebook';
    const PROVIDER_APPLE = 'apple';

    protected $connection = ConnectionDB::PG_SQL;

    protected $table = 'user_oauth';

    protected $fillable = [
        'name',
        'user_id',
        'provider',
        'provider_id',
        'provider_token',
        'avatar',
        'created_at',
        'updated_at',
        'deleted_at',
        'nonce',
    ];

    protected $hidden = [
        'nonce',
    ];

    public function user()
    {
        return $this->belongsTo(AuthEncryptedModel::class, 'user_id');
    }

    public function getNameAttribute()
    {
        return $this->decryptor()->decrypt($this->attributes['name']);
    }
}
